### ISSUE TITLE
Code Announcement

### ISSUE THREAD

**Issue by luck-grz** [robot-learning-freiburg/MDPCalib#2]
Hello, I would like to announce the code。Thank you。

**Comment by vniclas** [comment]
Hi, thanks for your interest in our work.

For licensing reasons, we will release the code upon acceptance of the used point correspondence network [CMRNext](http://cmrnext.cs.uni-freiburg.de/).

**Comment by vniclas** [comment]
We released the code for coarse registration. The refinement will follow upon the public release of CMRNext.
